using InControl;
using System;
using UnityEngine;

public class PlayerInput
{
	public string PlayerDevice;
	public int PlayerID;

	public float HorizontalMovement;
	public float VerticalMovement;
	public float HorizontalAim;
	public float VerticalAim;

	public bool PushTransmission;
	public bool PullTransmission;

	public bool Menu;
	public bool Select;

	public Vector3 GetNormalizedAim(Vector3 originPoint, Camera screenCamera)
	{
		if (PlayerDevice != InputManager.KEYBOARD_AND_MOUSE)
			return new Vector3(HorizontalAim, VerticalAim).normalized;

		var aimVec = (screenCamera.ScreenToWorldPoint(new Vector3(HorizontalAim, VerticalAim)) - originPoint).normalized;
		aimVec.z = 0;
		return aimVec;
	}

	public override string ToString()
	{
		return $@"Player: ({PlayerID})
Input Device: ({PlayerDevice})
Movement: ({HorizontalMovement}, {VerticalMovement})
Aim: ({HorizontalAim}, {VerticalAim})
Push: ({PushTransmission})
Pull: ({PullTransmission})
Menu: ({Menu})
Select: ({Select})";
	}
}

public class InputManager : MonoBehaviour
{
	public const string KEYBOARD_AND_MOUSE = "Keyboard and Mouse";

	private class InputMode
	{
		public bool IsKeyboardAndMouse;
		public InControl.InputDevice InputDevice;
	}

	#region Singleton

	private static InputManager instance;

	private void MakeSingleton()
	{
		if (instance != null && instance != this)
		{
			Destroy(this);
		}

		instance = this;
	}

	#endregion

	private const int MAX_PLAYERS = 4;

	public static Action<int> OnResetPlayerDevices;

	private InputMode[] playerDevices = new InputMode[MAX_PLAYERS];
	private PlayerInput[] playerInputs = new PlayerInput[MAX_PLAYERS];

	#region Unity Hooks

	private void Awake()
	{
		MakeSingleton();

		ResetPlayerDevices();
		InControl.InputManager.OnDeviceAttached += inputDevice => { Debug.Log($"Device [{inputDevice.Name}] attached"); };
		InControl.InputManager.OnDeviceDetached += inputDevice =>
		{
			Debug.Log($"Device [{inputDevice.Name}] detached");
			bool needsReset = false;
			foreach (var playerDevice in playerDevices)
			{
				if (playerDevice?.InputDevice == inputDevice)
				{
					needsReset = true;
					break;
				}
			}

			if (needsReset)
			{
				ResetPlayerDevices();
			}
			Debug.Log($"All devices reset!");
		};
	}

	private void FixedUpdate()
	{
		foreach (var inputDevice in InControl.InputManager.Devices)
		{
			if (!inputDevice.IsAttached || !inputDevice.IsKnown || !inputDevice.IsSupportedOnThisPlatform)
				continue;

			if (inputDevice.Command)
			{
				SetNextControllerPlayer(inputDevice);
			}
		}

		if (Input.GetKey(KeyCode.Space))
			SetNextKeyboardPlayer();
	}

	private void Update()
	{
		UpdatePlayerInputs();
	}

	private void OnGUI()
	{
		const bool DEBUG_GUI = false;
		if (DEBUG_GUI)
		{
			GUI.Label(new Rect(0, 0, 1000, 1000), $@"
Player 1:
{GetPlayerInput(0)}

Player 2:
{GetPlayerInput(1)}

Player 3:
{GetPlayerInput(2)}

Player 4:
{GetPlayerInput(3)}
");
		}
	}

	#endregion

	public static PlayerInput GetPlayerInput(int playerID)
	{
		return instance.playerInputs[playerID];
	}

	private void ResetPlayerDevices()
	{
		int numberOfOldDevices = 0;
		for (int i = 0; i < MAX_PLAYERS; i++)
		{
			if (playerDevices[i] != null)
				numberOfOldDevices++;

			playerDevices[i] = null;
			playerInputs[i] = new PlayerInput() { PlayerID = i };
		}

		OnResetPlayerDevices?.Invoke(numberOfOldDevices);
	}

	private void SetNextKeyboardPlayer()
	{
		const int INVALID = -1;
		int potentialPlayerID = INVALID;

		for (int i = 0; i < MAX_PLAYERS; i++)
		{
			if (playerDevices[i]?.IsKeyboardAndMouse ?? false)
				return;
			else if (playerDevices[i] == null && potentialPlayerID == INVALID)
				potentialPlayerID = i;
		}

		if (potentialPlayerID != INVALID)
		{
			Debug.Log($"Player {potentialPlayerID + 1} controller set to Keyboard and Mouse");
			playerDevices[potentialPlayerID] = new InputMode()
			{
				IsKeyboardAndMouse = true,
				InputDevice = null
			};
		}
	}

	private void SetNextControllerPlayer(InputDevice inputDevice)
	{
		const int INVALID = -1;
		int potentialPlayerID = INVALID;

		for (int i = 0; i < MAX_PLAYERS; i++)
		{
			if (playerDevices[i]?.InputDevice == inputDevice)
				return;
			else if (playerDevices[i] == null && potentialPlayerID == INVALID)
				potentialPlayerID = i;
		}

		if (potentialPlayerID != INVALID)
		{
			Debug.Log($"Player {potentialPlayerID + 1} controller set to {inputDevice.Name}");
			playerDevices[potentialPlayerID] = new InputMode()
			{
				IsKeyboardAndMouse = false,
				InputDevice = inputDevice
			};
		}
	}

	private void UpdatePlayerInputs()
	{
		for (int i = 0; i < MAX_PLAYERS; i++)
		{
			var inputMode = playerDevices[i];
			if (inputMode == null)
				continue;

			if (inputMode.IsKeyboardAndMouse)
				UpdateKeyboardAndMousePlayerInputs(i);
			else
				UpdateControllerPlayerInputs(i, inputMode.InputDevice);
		}
	}

	private void UpdateKeyboardAndMousePlayerInputs(int playerID)
	{
		var playerInput = playerInputs[playerID];
		playerInput.PlayerDevice = InputManager.KEYBOARD_AND_MOUSE;

		playerInput.HorizontalMovement =
			Input.GetKey(KeyCode.A) ? -1 : 0 +
			(Input.GetKey(KeyCode.D) ? 1 : 0);
		playerInput.VerticalMovement =
			Input.GetKey(KeyCode.S) ? -1 : 0 +
			(Input.GetKey(KeyCode.W) ? 1 : 0);

		playerInput.HorizontalAim = Input.mousePosition.x;
		playerInput.VerticalAim = Input.mousePosition.y;

		playerInput.PushTransmission = Input.GetKey(KeyCode.Mouse0);
		playerInput.PullTransmission = Input.GetKey(KeyCode.Mouse1);

		playerInput.Menu = Input.GetKey(KeyCode.Escape);
		playerInput.Select = Input.GetKey(KeyCode.Space);
	}

	private void UpdateControllerPlayerInputs(int playerID, InControl.InputDevice inputDevice)
	{
		if (inputDevice == null)
			return;

		var playerInput = playerInputs[playerID];
		playerInput.PlayerDevice = inputDevice.Name;

		playerInput.HorizontalMovement = inputDevice.LeftStick.X;
		playerInput.VerticalMovement = inputDevice.LeftStick.Y;

		playerInput.HorizontalAim = inputDevice.RightStick.X;
		playerInput.VerticalAim = inputDevice.RightStick.Y;

		playerInput.PushTransmission = inputDevice.RightTrigger;
		playerInput.PullTransmission = inputDevice.LeftTrigger;

		playerInput.Menu = inputDevice.Command;
		playerInput.Select = inputDevice.Action1;
	}
}